CREATE DATABASE `school` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER 'school'@'localhost' IDENTIFIED BY 'school';
CREATE USER 'school'@'%' IDENTIFIED BY 'school';

CREATE USER 'schoolsu'@'localhost' IDENTIFIED BY 'school';
CREATE USER 'schoolsu'@'%' IDENTIFIED BY 'school';

REVOKE ALL PRIVILEGES ON * . * FROM 'school'@'localhost';
REVOKE ALL PRIVILEGES ON * . * FROM 'school'@'%';

REVOKE ALL PRIVILEGES ON * . * FROM 'schoolsu'@'localhost';
REVOKE ALL PRIVILEGES ON * . * FROM 'schoolsu'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE ON school. * TO 'school'@'localhost'
  WITH GRANT OPTION
  MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0
  MAX_UPDATES_PER_HOUR 0
  MAX_USER_CONNECTIONS 0;

GRANT SELECT, INSERT, UPDATE, DELETE ON school. * TO 'school'@'%'
  WITH GRANT OPTION
  MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0
  MAX_UPDATES_PER_HOUR 0
  MAX_USER_CONNECTIONS 0;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE,
  ALTER, INDEX, DROP, CREATE TEMPORARY TABLES, SHOW VIEW,
  CREATE ROUTINE, ALTER ROUTINE, EXECUTE, CREATE VIEW, EVENT, TRIGGER,
  LOCK TABLES
  ON school. * TO 'schoolsu'@'localhost'
  WITH GRANT OPTION
  MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0
  MAX_UPDATES_PER_HOUR 0
  MAX_USER_CONNECTIONS 0;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE,
  ALTER, INDEX, DROP, CREATE TEMPORARY TABLES, SHOW VIEW,
  CREATE ROUTINE, ALTER ROUTINE, EXECUTE, CREATE VIEW, EVENT, TRIGGER,
  LOCK TABLES
  ON school. * TO 'schoolsu'@'%'
  WITH GRANT OPTION
  MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0
  MAX_UPDATES_PER_HOUR 0
  MAX_USER_CONNECTIONS 0;
